# Generated by Django 4.2.2 on 2023-06-08 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitrecord",
            name="record_date",
            field=models.DateField(
                default=datetime.datetime(2023, 6, 8, 2, 34, 27, 616209)
            ),
        ),
    ]
