# Generated by Django 4.2.2 on 2023-06-08 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0004_alter_habitrecord_record_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitrecord",
            name="record_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
